### ISSUE TITLE
bug: whether the exception information of repeated voting can be encapsulated into user-friendly info

### ISSUE THREAD

**Issue by zhanyeye** [nju-softeng/dingtalk-app-server#77]
https://github.com/nju-softeng/dingtalk-app-web/issues/29

#### 缺陷描述：
进入投票页面后，第一次投票，页面没有变化；第二次投票出现异常，但前端异常信息为null, (这里其实是后端 `Duplicate entry 'v_id-u_id' for key`, 重复投票的异常)

#### 问题分析：
投票后确实发送到后端了，但是前端没有正确切换到投票状态页面，后端异常信息也没提示 ”用户已投票“

+ 前端异常log：
```
POST http://47.104.103.33:8089/api/vote/52 500 ()
{timestamp: "2021-12-03", status: 500, error: "Internal Server Error", message: "", path: "/api/vote/52"}
```

+ 后端异常log:
```
Duplicate entry '52-27' for key 'vote_detail.UK61vpx1woxr2v6exm8a2hxwtgb'
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [vote_detail.UK61vpx1woxr2v6exm8a2hxwtgb]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '52-27' for key 'vote_detail.UK61vpx1woxr2v6exm8a2hxwtgb'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
........
```

**Comment by lilingj** [comment]
前端问题。投票后没刷新数据，试图重复投票后后端报异常。

**Comment by zhanyeye** [comment]
> 前端问题。投票后没刷新数据，试图重复投票后后端报异常。
我还没说完🤣

**Comment by zhanyeye** [comment]
+ 重复申请的 Exception 出现的位置，这里能不能捕获异常，提示用户呢~
https://github.com/nju-softeng/dingtalk-app-server/blob/d4a8309ed0e94a92fd3dac0c2521eeddc3683c17/src/main/java/com/softeng/dingtalk/service/VoteService.java#L192-L195
+ [拦截异常并封装的代码](https://github.com/nju-softeng/dingtalk-app-server/edit/main/src/main/java/com/softeng/dingtalk/controller/ExceptionController.java)
